// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGmXRCKt35Bt1oTyVQu9ixQtdeCJJjMFo',
    appId: '1:380094860543:web:d613e8380e7830f3d2d0ca',
    messagingSenderId: '380094860543',
    projectId: 'tiktok-jiun-zxc',
    authDomain: 'tiktok-jiun-zxc.firebaseapp.com',
    storageBucket: 'tiktok-jiun-zxc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZgBYI9lWOY7LBOWVCXpSFRQbL1VX81U',
    appId: '1:380094860543:android:7065d6219444448fd2d0ca',
    messagingSenderId: '380094860543',
    projectId: 'tiktok-jiun-zxc',
    storageBucket: 'tiktok-jiun-zxc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiHCFE8obL8cxnnRWjxdHKYO0qvIpDtaE',
    appId: '1:380094860543:ios:d90543e7bab49301d2d0ca',
    messagingSenderId: '380094860543',
    projectId: 'tiktok-jiun-zxc',
    storageBucket: 'tiktok-jiun-zxc.appspot.com',
    iosBundleId: 'com.example.tiktokClone2nd',
  );
}
